skillbackpack/portfolio/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    #url(r'^me/', detail_view, name='portfolio'),
    url(r'^accounts/profile/$', user_portfolio, name='account_redirect'),
    url(r'^accounts/profile/delete_summary/(?P<pk>\d+)/$', delete_summary, name="delete_summary"),
    url(r'^accounts/profile/education/$',add_education, name='education'),
    url(r'^accounts/profile/education/(?P<pk>\d+)/$',EducationUpdate.as_view(), name='education_update'),
    url(r'^accounts/profile/education/delete/(?P<pk>\d+)/$', delete_education, name='delete_education'),


    url(r'^accounts/profile/skill/$', add_skills, name='add_skill'),
    url(r'^accounts/portfolio/skills/delete/(?P<pk>\d+)/$', delete_skill, name='delete_skill'),
    url(r'^accounts/portfolio/skills/(?P<pk>\d+)/$', SkillUpdate.as_view(), name='update_skill'),


    url(r'^accounts/profile/experience/$', add_experience, name='add_experience'),
    url(r'^accounts/portfolio/experience/delete/(?P<pk>\d+)/$', delete_experience, name='delete_experience'),
    url(r'^accounts/portfolio/experience/(?P<pk>\d+)/$', ExperienceUpdate.as_view(), name='update_experience'),



    url(r'^accounts/profile/project/$', add_projects, name='add_projects'),
    url(r'^accounts/portfolio/project/delete/(?P<pk>\d+)/$', delete_project, name='delete_project'),
    url(r'^accounts/portfolio/project/(?P<pk>\d+)/$', ProjectUpdate.as_view(), name='update_project'),

    url(r'^accounts/portfolio/my_applications/$', my_applications, name='my_applications'),


    url(r'^accounts/employer/$', employer_portfolio, name="employer_portfolio"),
    url(r'^accounts/employer/delete_job/(?P<pk>\d+)/$', DeleteJobs.as_view(), name="job_delete"),
    url(r'^accounts/employer/job_details/(?P<pk>\d+)/$', job_details, name="job_details"),

    url(r'^accounts/employers_list/$', employers_list, name='employers_list'),
    url(r'^accounts/employer_details/(?P<pk>\d+)/$', employer_details, name="employer_details"),
    url(r'^accounts/employer_details/job_application/(?P<pk>\d+)/$', job_application, name="job_application"),


    url(r'^accounts/candidates_list/(?P<pk>\d+)/$', candidates_list, name="candidates_list"),
    url(r'^accounts/candidate_details/(?P<pk>\d+)/$', candidate_details, name="candidate_details"),

]

skillbackpack/skillbackpack/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout
from django.conf.urls import url, include
from portfolio import views as portfolio_views
from user_management import views as user_views

urlpatterns = [
    url(r'^$', portfolio_views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^portfolio/', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    url(r'^portfolio/', include(('user_management.urls', 'user_management'), namespace='user_management')),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^accounts/login/$', user_views.signin, name='login'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

skillbackpack/user_management/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
        url(r'^employer_login/', signin_employer, name='employer_login'),

]

skillbackpack/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <script src="{% static 'js/jquery-3.1.0.js' %}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% block head %}
  <title>Skill Backpack</title>
  {% endblock %}
</head>



<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Skillbackpack</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item navbar-right">
          <a class="nav-link" href={% url 'user_management:employer_login' %}>Employers</a>
        </li>

      </ul>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item ml-auto">
          {% if user.is_authenticated %}
          {% if is_emp %}
          <a class="nav-link " href={% url 'portfolio:employer_portfolio' %}>{{user.first_name}} Portfolio</a>
        <li class="nav-item ml-auto">
          <a class="nav-link " href={% url 'logout' %}>Logout</a>
        </li>
            {% else %}
          <li class="nav-item ml-auto">
            <a class="nav-link ml-auto" href={% url 'portfolio:account_redirect' %}>My Portfolio</a>
          </li>
            {%endif%}
        {% else %}
        <li class="nav-item ml-auto">
            <a class="nav-link ml-auto" href={% url 'login' %}>Login</a>
        </li>

        {%endif%}
        </li>
      </ul>
    </div>
  </nav>
  {%block content%}

  {%endblock%}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <footer class="footer fixed-bottom">
    <div class="container">
      <br />
      <div class="copyright">
        <p style="max-width:200px; margin-right: 10px !important;" class="bottomText"> Wanna Smile&copy; 2018</p>
      </div>
    </div>
  </footer>
</body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->


</html>

skillbackpack/templates/profile_base.html
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar_style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />


    <title>User Profile</title>
    {% block css %} {% endblock %}
</head>



    <body>
      <div class="wrapper">
      <!-- Sidebar -->
      <nav id="sidebar">
          <div class="sidebar-header">
            <img src="https://www.theouterbankshospital.com/OuterBanksHospital/Images/Vidant_Default_Profile.png" style="margin-left: -10px;" alt="">
            <br>
            <br>
              <h3>{{user.first_name}} {{user.last_name}}</h3>
          </div>
          <ul class="list-unstyled components" style="margin-top:-20px;">
              <li>
              <a href={% url 'portfolio:account_redirect' %}>My Portfolio</a>
              </li>
              <li>
                  <a href={%url 'portfolio:employers_list' %}>Search Employers</a>

              </li>

              <li>
                  <a href={%url 'portfolio:my_applications' %}>My Applications</a>
              </li>
              <li>
                  <a href={% url 'logout' %}>Logout</a>
              </li>
          </ul>

        </nav>
        <!-- Page Content -->
        <div class=""id="content" style="margin-left:10px; margin-right:10px">
            {%block content%}
            {%endblock%}

        </div>
    </div>

</body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->


</html>