skillbackpack/portfolio/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    #url(r'^me/', detail_view, name='portfolio'),
    url(r'^accounts/profile/$', user_portfolio, name='account_redirect'),
    url(r'^accounts/profile/delete_summary/(?P<pk>\d+)/$', delete_summary, name="delete_summary"),
    url(r'^accounts/profile/education/$',add_education, name='education'),
    url(r'^accounts/profile/education/(?P<pk>\d+)/$',EducationUpdate.as_view(), name='education_update'),
    url(r'^accounts/profile/education/delete/(?P<pk>\d+)/$', delete_education, name='delete_education'),


    url(r'^accounts/profile/skill/$', add_skills, name='add_skill'),
    url(r'^accounts/portfolio/skills/delete/(?P<pk>\d+)/$', delete_skill, name='delete_skill'),
    url(r'^accounts/portfolio/skills/(?P<pk>\d+)/$', SkillUpdate.as_view(), name='update_skill'),


    url(r'^accounts/profile/experience/$', add_experience, name='add_experience'),
    url(r'^accounts/portfolio/experience/delete/(?P<pk>\d+)/$', delete_experience, name='delete_experience'),
    url(r'^accounts/portfolio/experience/(?P<pk>\d+)/$', ExperienceUpdate.as_view(), name='update_experience'),



    url(r'^accounts/profile/project/$', add_projects, name='add_projects'),
    url(r'^accounts/portfolio/project/delete/(?P<pk>\d+)/$', delete_project, name='delete_project'),
    url(r'^accounts/portfolio/project/(?P<pk>\d+)/$', ProjectUpdate.as_view(), name='update_project'),

    url(r'^accounts/portfolio/my_applications/$', my_applications, name='my_applications'),


    url(r'^accounts/employer/$', employer_portfolio, name="employer_portfolio"),
    url(r'^accounts/employer/delete_job/(?P<pk>\d+)/$', DeleteJobs.as_view(), name="job_delete"),
    url(r'^accounts/employer/job_details/(?P<pk>\d+)/$', job_details, name="job_details"),

    url(r'^accounts/employers_list/$', employers_list, name='employers_list'),
    url(r'^accounts/employer_details/(?P<pk>\d+)/$', employer_details, name="employer_details"),
    url(r'^accounts/employer_details/job_application/(?P<pk>\d+)/$', job_application, name="job_application"),


    url(r'^accounts/candidates_list/(?P<pk>\d+)/$', candidates_list, name="candidates_list"),
    url(r'^accounts/candidate_details/(?P<pk>\d+)/$', candidate_details, name="candidate_details"),

]

skillbackpack/skillbackpack/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout
from django.conf.urls import url, include
from portfolio import views as portfolio_views
from user_management import views as user_views

urlpatterns = [
    url(r'^$', portfolio_views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^portfolio/', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    url(r'^portfolio/', include(('user_management.urls', 'user_management'), namespace='user_management')),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^accounts/login/$', user_views.signin, name='login'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

skillbackpack/portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
from user_management.models import Employer
from django.utils import timezone
from .skills_list import skill_list


# Defines the various database tables for the project.
# Please refer to the report for a detailed description of the database schema.


class Summary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    summary = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.summary)



class Education(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    university = models.CharField(max_length=100, default=None)
    course = models.CharField(max_length=150, default=None)
    gpa = models.DecimalField(null=True, max_digits=4, decimal_places=2)
    description = models.TextField(default=None)
    date_start = models.DateField(default=None)
    date_end = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Education"
        unique_together = ('user', 'university', 'course')

    def __str__(self):
        return str(self.university)


class Skill(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choices = [(str(x),y) for x, y in enumerate(skill_list)]
    name = models.CharField(max_length=3, choices=choices)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Skill"
        unique_together = ('user', 'name')

    def __str__(self):
        return str(self.name)


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    date_start = models.DateField()
    date_grad = models.DateField(null=True)

    class Meta:
        verbose_name_plural = "Project"
        unique_together = ('user', 'name')

    def __str__(self):
        return str(self.name)


class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    date_start = models.DateField(default=None)
    date_end = models.DateField(null=True)

    class Meta:
        verbose_name_plural = "Experience"
        unique_together = ('user', 'organization', 'role')

    def __str__(self):
        return str(self.organization) + " " + str(self.role)



class Jobs(models.Model):
    job_poster = models.ForeignKey(Employer, on_delete=models.CASCADE)
    job_title = models.CharField(max_length = 255, default=None)
    date_posted = models.DateField(default=timezone.now, blank=True, null=True)
    date_expiry = models.DateField(default=None)
    job_description = models.TextField()

    class Meta:
        verbose_name_plural = "Jobs"

    def __str__(self):
        return str(self.job_title)

    def get_absolute_url(self):
        return reverse('portfolio:employer_portfolio')


class SkillsRequired(models.Model):
    job = models.ForeignKey(Jobs, on_delete=models.CASCADE)
    # skills_choices = [(str(x),y) for x, y in enumerate(skill_list)]
    skill = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Skills Required"
        unique_together = ("job", "skill")


class Job_Applications(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Jobs, on_delete=models.CASCADE)
    date_applied = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Job Applications'
        unique_together = ('candidate', 'job')

skillbackpack/portfolio/views.py
from django.shortcuts import redirect, HttpResponse, HttpResponseRedirect, reverse
from rating.apps.apps import get_search, update_skill_rating
from django.core.mail import send_mail, EmailMultiAlternatives
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.template.loader import get_template
from user_management.models import Employer
from django.template.defaulttags import register
from django.urls import reverse_lazy
from .skills_list import skill_list
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from .forms import *
from .models import *
import json

# Create your views here.
def sendEmail(subject, content, recipient_list, text_content='', from_email=settings.EMAIL_HOST_USER):
    """
        Function to send emails to a list of recipients.
    """
    msg = EmailMultiAlternatives(subject, text_content, from_email, recipient_list)
    msg.attach_alternative(content, "text/html")
    msg.send()
    return None


#Render Homepage view.
def index(request):
    template = "portfolio/home.html"
    user = request.user
    users = User.objects.all()
    for usr in users:
        update_skill_rating(usr)
    is_emp=False
    if not user.is_anonymous:
        is_emp = Employer.objects.filter(username=user).exists()

    return render(request, template, {"is_emp": is_emp})

#Renders the user portfolio
@login_required # decorator to restrict access for anonymous users
def user_portfolio(request):
    template = 'portfolio/index2.html'

    if request.method == "GET":
        user = request.user
        summary = Summary.objects.filter(user=user)
        summary_form = None
        if len(summary)==0:
            summary_form = SummaryForm()

        educations = Education.objects.filter(user=user)
        skills = Skill.objects.filter(user=user)
        experieces = Experience.objects.filter(user=user)
        projects = Project.objects.filter(user=user)
        return render(request, template, context={'portfolio':user, 'educations':educations, 'skills':skills, 'experiences':experieces, 'summary':summary, 'projects':projects,
        'summary_form': summary_form})

    # Edit summary. Displayed on the portoflio page to update summary section.
    if request.method == "POST":
        form = SummaryForm(request.POST)
        user = request.user
        if form.is_valid():
            summary = form.cleaned_data.get('summary')
            user_summary = Summary.objects.create(user=user, summary=summary)

            return redirect('portfolio:account_redirect')

    return HttpResponseRedirect(reverse("portfolio:account_redirect"))

# View to delete summary.
@login_required
def delete_summary(request, pk):
    summary = Summary.objects.filter(id=pk).delete()
    return redirect('portfolio:account_redirect')


# Adds new education field for a user
# update_skill_rating function is called whenever education, skills, projects and experience
# database instances are created or updated.
# This allows the recalculation of portfolio rating for individual skills.
@login_required
def add_education(request):

    template = 'portfolio/add_education.html'
    if request.method == "GET":
        user = request.user
        form = EducationForm()
        return render(request, template, {'user': user, 'form':form})

    else:
        form = EducationForm(request.POST)
        print(form)
        user = request.user
        if form.is_valid():
            university = form.cleaned_data.get('university')
            course = form.cleaned_data.get('course')
            gpa = form.cleaned_data.get('gpa')
            description = form.cleaned_data.get('description')
            date_start = form.cleaned_data.get('date_start')
            date_end = form.cleaned_data.get('date_end')
            education = Education.objects.create(user=user, university=university,course=course, gpa=gpa, description=description, date_start=date_start, date_end =date_end)
            update_skill_rating(request.user)
            return redirect('portfolio:account_redirect')
        return render(request, template, {'user': user, 'form':form})

# View to delete individual education
def delete_education(request, pk):
    education = Education.objects.filter(id=pk).delete()
    update_skill_rating(request.user)
    return redirect('portfolio:account_redirect')

# ClassBased View to update Education section.
# ClassBased Generic UpdateView makes it easy to update a database model instance.
# LoginRequiredMixin is used to restrict access for users who are not logged in.
class EducationUpdate(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = Education
    context_object_name = 'education'
    form_class = EducationForm
    template_name = 'portfolio/update_education.html'
    success_url = reverse_lazy('portfolio:account_redirect')
    def post(self, request, **kwargs):
        update_skill_rating(request.user)
        return super(EducationUpdate, self).post(request, **kwargs)

# Add new skills
@login_required
def add_skills(request):
    template = template = 'portfolio/add_skill.html'

    if request.method == "GET":
        user = request.user
        form = SkillsForm()
        return render(request, template, {'form':form})

    else:
        form = SkillsForm(request.POST)
        user = request.user
        if form.is_valid():
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            skill = Skill.objects.create(user=user, name=name, description=description)

            update_skill_rating(user)   # update the skill rating for the user whenever a new skill is added
            return redirect('portfolio:account_redirect')
    return render(request, template, {'form':form})

#Delete a skill
@login_required
def delete_skill(request, pk):
    skill = Skill.objects.get(id=pk).delete()
    # update skill ratings when a skill is deleted
    update_skill_rating(request.user)
    return redirect('portfolio:account_redirect')

# Update an existing skill
class SkillUpdate(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = Skill
    context_object_name = 'skill'
    form_class = SkillsForm
    template_name = 'portfolio/update_skill.html'
    success_url = reverse_lazy('portfolio:account_redirect')

    # update the skill rating whenever a skill is updated
    def post(self, request, **kwargs):
        update_skill_rating(request.user)
        return super(SkillUpdate, self).post(request, **kwargs)

# Add experience view
@login_required
def add_experience(request):
    template = 'portfolio/add_experience.html'

    if request.method == "GET":
        user = request.user
        form = ExperienceForm()
        return render(request, template, {'form':form})

    else:
        form = ExperienceForm(request.POST)
        user = request.user
        if form.is_valid():
            organization = form.cleaned_data.get('organization')
            role = form.cleaned_data.get('role')
            description = form.cleaned_data.get('description')
            date_start = form.cleaned_data.get('date_start')
            date_end = form.cleaned_data.get('date_end')
            experiece = Experience.objects.create(user=user, organization=organization, description=description, role=role, date_start=date_start, date_end=date_end)

            # update skill rating when a new experience is added
            update_skill_rating(request.user)
            return redirect('portfolio:account_redirect')
    return render(request, template, {'form': form})

#delete experience instance and update skill ratings
def delete_experience(request, pk):
    experience = Experience.objects.get(id=pk).delete()
    update_skill_rating(request.user)
    return redirect('portfolio:account_redirect')

# Update experience and respective skill ratings
class ExperienceUpdate(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = Experience
    context_object_name = 'experience'
    form_class = ExperienceForm
    template_name = 'portfolio/update_experience.html'
    success_url = reverse_lazy('portfolio:account_redirect')

    def post(self, request, **kwargs):
        update_skill_rating(request.user)
        return super(ExperienceUpdate, self).post(request, **kwargs)


# Add new projects
@login_required
def add_projects(request):
    template = 'portfolio/add_projects.html'
    if request.method == "GET":
        user = request.user
        form = ProjectForm()
        return render(request, template, {'form':form})

    else:
        form = ProjectForm(request.POST)
        user = request.user
        if form.is_valid():
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            date_start = form.cleaned_data.get('date_start')
            date_grad = form.cleaned_data.get('date_grad')
            project = Project.objects.create(user=user, name=name, description=description, date_start=date_start, date_grad=date_grad)
            update_skill_rating(request.user)
            return redirect('portfolio:account_redirect')

# delete projects
@login_required
def delete_project(request, pk):
    project = Project.objects.get(id=pk).delete()
    update_skill_rating(request.user)
    return redirect('portfolio:account_redirect')

#Update existing projects and skill ratings accordingly
class ProjectUpdate(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm
    template_name = 'portfolio/update_project.html'
    success_url = reverse_lazy('portfolio:account_redirect')

    def post(self, request, **kwargs):
        update_skill_rating(request.user)

skillbackpack/templates/portfolio/add_education.html
{% extends "profile_base.html" %} {% block content %}


{% for err in errors  %}
  <p>{{err}}</p>
{% endfor %}


<form class="pl-5" action={% url 'portfolio:education' %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <div class="form-group row pt-1 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">University Name:</label>
    <div class="col-sm-9">
      {{form.university}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Degree Name:</label>
    <div class="col-sm-9">
      {{form.course}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">GPA:</label>
    <div class="col-sm-9">
      {{form.gpa}}
    </div>
  </div>



  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Start Date:</label>

    <div class="col-sm-9">
      {{form.date_start}}
    </div>

    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>


  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Graduate Date:</label>

    <div class="col-sm-9">
      {{form.date_end}}
    </div>
    <script>
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>


  <div class="form-group row pt-2 pb-4">
    <label for="id_description" class="col-sm-2 col-form-label">Description :</label>
    <div class="col-sm-9">
      {{form.description}}
    </div>
  </div>

  <div class="text-center pt-2">
    <input type="submit" name="" class="btn btn-primary" value="Add Education">
    <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>
</form>
{% endblock %}

skillbackpack/templates/portfolio/add_experience.html
{% extends "profile_base.html" %} {% block content %}
<form class="pl-5" action={% url 'portfolio:add_experience' %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <div class="form-group row pt-1 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Company Name :</label>
    <div class="col-sm-9">
      {{form.organization}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Role :</label>
    <div class="col-sm-9">
      {{form.role}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Description :</label>
    <div class="col-sm-9">
      {{form.description}}
    </div>
  </div>

  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Start Date :</label>
    <div class="col-sm-9">
      {{form.date_start}}
      {% for error in form.date_start.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">End Date :</label>
    <div class="col-sm-9">
      {{form.date_end}}
      {% for error in form.date_end.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="text-center pt-2">
    <input type="submit" name="" class="btn btn-primary" value="Add Experience">
    <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>
  </div>
</form>
{% endblock %}

skillbackpack/templates/portfolio/add_projects.html
{% extends "profile_base.html" %} {% block content %}
<form class="pl-5" action={% url 'portfolio:add_projects' %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <div class="form-group row pt-1 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Project Name:</label>
    <div class="col-sm-9">
      {{form.name}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Description:</label>
    <div class="col-sm-9">
      {{form.description}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Start Date:</label>
    <div class="col-sm-9">
      {{form.date_start}}
      {% for error in form.date_start.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">End Date:</label>
    <div class="col-sm-9">
      {{form.date_grad}}
      {% for error in form.date_end.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="text-center pt-2">
    <input type="submit" name="" class="btn btn-primary" value="Add Project">
    <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>
  </div>
</form>
{% endblock %}

skillbackpack/templates/portfolio/update_education.html
{% extends "profile_base.html" %} {% block content %}


{% for err in errors  %}
  <p>{{err}}</p>
{% endfor %}


<form class="pl-5" action={% url 'portfolio:education_update' pk=education.id %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <div class="form-group row pt-1 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">University Name:</label>
    <div class="col-sm-9">
      {{form.university}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Degree Name:</label>
    <div class="col-sm-9">
      {{form.course}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">GPA:</label>
    <div class="col-sm-9">
      {{form.gpa}}
    </div>
  </div>



  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Start Date:</label>

    <div class="col-sm-9">
      {{form.date_start}}
    </div>

    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>


  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Graduate Date:</label>

    <div class="col-sm-9">
      {{form.date_end}}
    </div>
    <script>
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>


  <div class="form-group row pt-2 pb-4">
    <label for="id_description" class="col-sm-2 col-form-label">Description :</label>
    <div class="col-sm-9">
      {{form.description}}
    </div>
  </div>

  <div class="text-center pt-2">
    <input type="submit" name="" class="btn btn-primary" value="Update Education">
    <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>
</form>
{% endblock %}

skillbackpack/templates/portfolio/update_experience.html
{% extends "profile_base.html" %} {% block content %}
<form class="pl-5" action={% url 'portfolio:update_experience' pk=experience.id %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <div class="form-group row pt-1 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Company Name :</label>
    <div class="col-sm-9">
      {{form.organization}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Role :</label>
    <div class="col-sm-9">
      {{form.role}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Description :</label>
    <div class="col-sm-9">
      {{form.description}}
    </div>
  </div>

  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Start Date :</label>
    <div class="col-sm-9">
      {{form.date_start}}
      {% for error in form.date_start.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">End Date :</label>
    <div class="col-sm-9">
      {{form.date_end}}
      {% for error in form.date_end.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="text-center pt-2">
    <input type="submit" name="" class="btn btn-primary" value="Update Experience">
    <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>
  </div>
</form>
{% endblock %}

skillbackpack/templates/portfolio/update_project.html
{% extends "profile_base.html" %} {% block content %}
<form class="pl-5" action={% url 'portfolio:update_project' pk=project.id %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->
  <div class="form-group row pt-1 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Project Name:</label>
    <div class="col-sm-9">
      {{form.name}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Description:</label>
    <div class="col-sm-9">
      {{form.description}}
    </div>
  </div>
  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">Start Date:</label>
    <div class="col-sm-9">
      {{form.date_start}}
      {% for error in form.date_start.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="form-group row pt-2 pb-2">
    <label for="id_name" class="col-sm-2 col-form-label">End Date:</label>
    <div class="col-sm-9">
      {{form.date_grad}}
      {% for error in form.date_end.errors %}
      <div class="alert text-danger">
          {{error}}
      </div>
      {% endfor %}
    </div>
    <script>
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>
  </div>

  <div class="text-center pt-2">
    <input type="submit" name="" class="btn btn-primary" value="Update Project">
    <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>
  </div>
</form>
{% endblock %}

skillbackpack/templates/portfolio/update_skill.html
{% extends "profile_base.html" %}
{% block content %}
<form class="pl-5" action={% url 'portfolio:update_skill' pk=skill.id %} method="post">
  {% csrf_token %}
  <!-- {{form.as_p}} -->

  <div class="form-group row pt-2 pb-2">
    <label for="id_name"class="col-sm-2 col-form-label">Name</label>
      <div class="col-sm-9">
        {{form.name}}
      </div>
  </div>

  <div class="form-group row pt-2 pb-4">
    <label for="id_description" class="col-sm-2 col-form-label">Description</label>
      <div class="col-sm-9">
        {{form.description}}
      </div>
  </div>

  <div class="text-center">
      <input type="submit" name="" class="btn btn-primary" value="Update Skill">
      <a href={% url 'portfolio:account_redirect' %} class="btn btn-primary" }>Cancel</a>
  </div>


</form>

{% endblock %}